// Generates src/app/core/api/generated/{auth,availability,booking}.d.ts from the gateway's
// Development OpenAPI documents. Nothing is written unless all three documents succeed.
import { mkdirSync, renameSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

export const SERVICES = ['auth', 'availability', 'booking'];
export const HEADER = '/* generated by pnpm gen:api, do not edit */\n/* eslint-disable */\n';
const DEFAULT_GATEWAY = 'http://localhost:5290';
const TIMEOUT_MS = 10_000;

export class GenApiError extends Error {}

async function fetchDocument(fetchFn, url) {
  const hint = `Cannot reach ${url}. Start the stack in Development (docker compose up) or set GATEWAY_URL.`;
  let response;
  try {
    response = await fetchFn(url, { signal: AbortSignal.timeout(TIMEOUT_MS) });
  } catch {
    throw new GenApiError(hint);
  }
  if (!response.ok) throw new GenApiError(`${hint} (HTTP ${response.status})`);
  let json;
  try {
    json = await response.json();
  } catch {
    throw new GenApiError(`${hint} (the body is not JSON)`);
  }
  if (!json || typeof json !== 'object' || !('openapi' in json)) {
    throw new GenApiError(`${hint} (the body is not an OpenAPI document)`);
  }
  return json;
}

/**
 * @param {{ fetch?: typeof fetch, gatewayUrl?: string, outDir: string,
 *   convert: (doc: object) => Promise<string> }} options
 */
export async function generate({ fetch: fetchFn = fetch, gatewayUrl, outDir, convert }) {
  const base = (gatewayUrl || DEFAULT_GATEWAY).replace(/\/+$/, '');
  const buffers = new Map();
  for (const name of SERVICES) {
    const url = `${base}/openapi/${name}/v1.json`;
    const doc = await fetchDocument(fetchFn, url);
    buffers.set(name, HEADER + (await convert(doc)));
  }
  mkdirSync(outDir, { recursive: true });
  const temps = [];
  for (const [name, text] of buffers) {
    const target = join(outDir, `${name}.d.ts`);
    writeFileSync(`${target}.tmp`, text);
    temps.push([`${target}.tmp`, target]);
  }
  for (const [tmp, target] of temps) renameSync(tmp, target);
  return [...buffers.keys()].map((n) => join(outDir, `${n}.d.ts`));
}

async function main() {
  const { default: openapiTS, astToString } = await import('openapi-typescript');
  const outDir = fileURLToPath(new URL('../src/app/core/api/generated/', import.meta.url));
  try {
    const files = await generate({
      gatewayUrl: process.env.GATEWAY_URL,
      outDir,
      convert: async (doc) => astToString(await openapiTS(doc)),
    });
    for (const f of files) console.log(`wrote ${f}`);
  } catch (error) {
    if (error instanceof GenApiError) {
      console.error(error.message);
      process.exit(1);
    }
    throw error;
  }
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) await main();
